### PR TITLE
Feat 865

### LINKED ISSUE #865: ✨[Feature] Enable debug logging with a context
**Is your feature request related to a problem? Please describe.**

Right now seems like users don't know how or don't enable debug logging. We can probably add some syntax to make this easier.

**Describe the solution you'd like**

I would love to see something like: 

```py
import torch_tensorrt as torchtrt 

with torchtrt.debug:
    torchtrt.ts.compile(....)

```

under the hood this would be equivalent to:

 ```py
import torch_tensorrt as torchtrt 

torchtrt.logging.set_reportable_log_level(torchtrt.logging.Level.Debug)
torchtrt.ts.compile(....)
torchtrt.logging.set_reportable_log_level(torchtrt.logging.Level.Error)
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by narendasan**
# Description

Adds context managers to quickly change the log level for a subset of code

Fixes #865 

## Type of change

Please delete options that are not relevant and/or add your own.

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by narendasan** [comment]
@peri044 what do you think of the names here, I think in a vacuum they make more sense but it might be confusing transitioning from the old tools. Ideally this becomes what people use 99% of the time though

**Comment by narendasan** [comment]
Reminder for myself to squash and merge this when its ready

**Review by peri044 — APPROVED** [review]
LGTM. One question is 
are we doing `with torch_tensorrt.logging.debug():` or `with torch_tensorrt.debug():`. 
The latter is described in the feature request https://github.com/NVIDIA/Torch-TensorRT/issues/865
Any preference here ?

**Comment by narendasan** [comment]
I think logging debug is better
________________________________

**Pull request merged**
