### PR TITLE
refactor: Restructured python perf benchmark tool

### PR DESCRIPTION
**Pull request by andi4191**
Signed-off-by: Anurag Dixit <anuragd@nvidia.com>

# Description
Re structured the python perf benchmark suite. Moved it to tools 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
 
# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by narendasan** [comment]
Do you think we need the C++ benchmark as well?, maybe we have two subdirectories in //tools/perf one for the tool you wrote (we could call this benchmark or if you have an name you like) and the other one could be like cpp_bench or something

**Comment by andi4191** [comment]
@narendasan : This benchmark tool simply expects the .jit.pt or TRT engine file in the configuration to run perf tests. CPP benchmark example has a reference sample to generate and export a TS module. Hence, this tool simply refers to it for example.

**Comment by narendasan** [comment]
Yeah I mean we can change the role of the cpp_benchmark tool. The only reason we output an engine is to test with trtexec. It wasnt *really* intended to be an example other than to define a benchmarking procedure.

**Comment by andi4191** [comment]
@narendasan : Can you take a look at this MR now? I have incorporated changes against the review comment.

**Review by narendasan — COMMENTED** [review]
Why is the training recipe being moved?

**Comment by andi4191** [comment]
> Why is the training recipe being moved?

Training recipe is still inside the examples/ and not being moved to tools/
It was under int8. It is a simple training recipe. Why does it need to be in examples/int8?

**Comment by narendasan** [comment]
I mean its not really used for anything else from a user perspective

**Comment by andi4191** [comment]
This PR is tracked here: https://github.com/NVIDIA/Torch-TensorRT/pull/879

Closing this PR

**Pull request closed without merging**
