### PR TITLE
Add CitriNet Notebook

### PR DESCRIPTION
**Pull request by mengdih**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by narendasan** [comment]
Notebook looks good, can you add it to the index in the documentation? https://github.com/NVIDIA/Torch-TensorRT/blob/master/docsrc/index.rst

**Comment by narendasan** [comment]
Also @mengdih please sign your commits

**Comment by narendasan** [comment]
I think you need to squash these commits into one, DCO is still complaining about the original commit. Every commit needs to be signed.

**Comment by vinhngx** [comment]
This branch is very outdated. "This branch is 2 commits ahead, 1491 commits behind NVIDIA:master."
I suggest forking an up to date master branch, then add the new notebook, also make change to README file, then make another PR.

**Comment by narendasan** [comment]
Bump on this PR @mengdih @vinhngx

**Comment by vinhngx** [comment]
Alternative MR submitted: https://github.com/NVIDIA/Torch-TensorRT/pull/984
Pls kindly close this request @narendasan .

**Pull request closed without merging**
