### PR TITLE
Correct typos in documents

### PR DESCRIPTION
**Pull request by yoshida-ryuhei**
# Description

Correct typos in documents.

## Type of change
- This change requires a documentation update

# Checklist:

- ~[ ] My code follows the style guidelines of this project (You can use the linters)~
- [x] I have performed a self-review of my own code
- ~[ ] I have commented my code, particularly in hard-to-understand areas and hacks~
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have added tests to verify my fix or my feature~
- ~[ ] New and existing unit tests pass locally with my changes~

I am not sure that correcting this directory `docs/_sources/` is adequate or not.
If I should correct another directory, plese let me know.

### CODE REVIEW

**Review by peri044 — APPROVED** [review]

**Comment by narendasan** [comment]
Thanks for the fixes. However, you are editing the pre rendered docs and not the doc source (//docsrc). Just modifying the rst files will be sufficient. CI will build the docs for you

**Comment by yoshida-ryuhei** [comment]
Thanks for reviewing my pull request.
I overlooked the directory `//docsrc` folder. So, I will correct the `//docsrc`.

**Comment by yoshida-ryuhei** [comment]
Now I have changed the directory to correct the document.
I am happy if you review the code.

**Review by narendasan — APPROVED** [review]
LGTM

**Pull request merged**
