### PR TITLE
feat: torchtrtc using atol and rtol for tolerance test

### PR DESCRIPTION
**Pull request by andi4191**
Signed-off-by: Anurag Dixit <a.dixit91@gmail.com>

# Description
Added rtol + atol tolerance check for torchtrtc. Similar to what we have for test benchmarks.

Fixes # (issue)
#1030 
## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by narendasan — COMMENTED** [review]
I think theres a threshold CLI argument we need to change as well

**Comment by andi4191** [comment]
> I think theres a threshold CLI argument we need to change as well

We still need this threshold value for comparison. Is this what you are referring to?
https://github.com/NVIDIA/Torch-TensorRT/blob/master/cpp/bin/torchtrtc/main.cpp#L124

OR 

do you want the atol and rtol to be configurable using CLI as well?

**Comment by narendasan** [comment]
I think both should be configurable

**Comment by andi4191** [comment]
Closing this PR as it was created from my fork instead. 
PR for this feature can be tracked here: https://github.com/NVIDIA/Torch-TensorRT/pull/1052

**Pull request closed without merging**
